name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    test-image:
        runs-on: ubuntu-latest
        steps:
            - name: Simple Test
              run: echo "Testing!"
